AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  ExportManagerFunction:
    Type: AWS::Serverless::Function
    Handler: "index.handler"
    Runtime: "nodejs12.x"
    Properties: 
      Code: 
        S3Bucket: "googlesensei-logger-bucket"
        S3Key: "Lambda/export-lambda.zip" # path
      Environment: 
      # lambda's valiables. you can change you hope for s3 naming
        Variables: 
          DestinationPrefix: process
          TaskName: export_task
      MemorySize: 128
      Role: "tmp-role-for-export-lambda"
      Timeout: 30

  CloudWatchEvents: # ここに必要数追加していく
    Type: AWS::Events::Rule
    Properties: 
      Description: "Kick Lambda"
      Name: "Kick-every-month"
      ScheduleExpression: "cron(0 12 1 * ? *)"
      State: DISABLED
      Targets:
          Arn: !GetAtt Lambda.Arn
          Id: "ExportManagerFunction"

  # LambdaのTriggerを宣言、CWEは複数
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref Lambda
      Principal: events.amazonaws.com
      SourceArn: !GetAtt CloudWatchEvents.Arn