AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ExportManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      Policies: {$your own role or create of below}

      // lambda's valiables. you can change you hope for s3 naming
      Environment:
        Variables:
          DestinationPrefix: process
          TaskName: export_task